# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/karim/Work/AUC/Linear Algebra/Project"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/karim/Work/AUC/Linear Algebra/Project"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/karim/Work/AUC/Linear Algebra/Project/CMakeFiles" "/home/karim/Work/AUC/Linear Algebra/Project/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/karim/Work/AUC/Linear Algebra/Project/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sim

# Build rule for target.
sim: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sim
.PHONY : sim

# fast build rule for target.
sim/fast:
	$(MAKE) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/build
.PHONY : sim/fast

camera.o: camera.cpp.o

.PHONY : camera.o

# target to build an object file
camera.cpp.o:
	$(MAKE) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/camera.cpp.o
.PHONY : camera.cpp.o

camera.i: camera.cpp.i

.PHONY : camera.i

# target to preprocess a source file
camera.cpp.i:
	$(MAKE) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/camera.cpp.i
.PHONY : camera.cpp.i

camera.s: camera.cpp.s

.PHONY : camera.s

# target to generate assembly for a file
camera.cpp.s:
	$(MAKE) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/camera.cpp.s
.PHONY : camera.cpp.s

dependencies/src/gl3w.o: dependencies/src/gl3w.c.o

.PHONY : dependencies/src/gl3w.o

# target to build an object file
dependencies/src/gl3w.c.o:
	$(MAKE) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/dependencies/src/gl3w.c.o
.PHONY : dependencies/src/gl3w.c.o

dependencies/src/gl3w.i: dependencies/src/gl3w.c.i

.PHONY : dependencies/src/gl3w.i

# target to preprocess a source file
dependencies/src/gl3w.c.i:
	$(MAKE) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/dependencies/src/gl3w.c.i
.PHONY : dependencies/src/gl3w.c.i

dependencies/src/gl3w.s: dependencies/src/gl3w.c.s

.PHONY : dependencies/src/gl3w.s

# target to generate assembly for a file
dependencies/src/gl3w.c.s:
	$(MAKE) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/dependencies/src/gl3w.c.s
.PHONY : dependencies/src/gl3w.c.s

game.o: game.cpp.o

.PHONY : game.o

# target to build an object file
game.cpp.o:
	$(MAKE) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/game.cpp.o
.PHONY : game.cpp.o

game.i: game.cpp.i

.PHONY : game.i

# target to preprocess a source file
game.cpp.i:
	$(MAKE) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/game.cpp.i
.PHONY : game.cpp.i

game.s: game.cpp.s

.PHONY : game.s

# target to generate assembly for a file
game.cpp.s:
	$(MAKE) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/game.cpp.s
.PHONY : game.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/main.cpp.s
.PHONY : main.cpp.s

utilities/matrix.o: utilities/matrix.cpp.o

.PHONY : utilities/matrix.o

# target to build an object file
utilities/matrix.cpp.o:
	$(MAKE) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/utilities/matrix.cpp.o
.PHONY : utilities/matrix.cpp.o

utilities/matrix.i: utilities/matrix.cpp.i

.PHONY : utilities/matrix.i

# target to preprocess a source file
utilities/matrix.cpp.i:
	$(MAKE) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/utilities/matrix.cpp.i
.PHONY : utilities/matrix.cpp.i

utilities/matrix.s: utilities/matrix.cpp.s

.PHONY : utilities/matrix.s

# target to generate assembly for a file
utilities/matrix.cpp.s:
	$(MAKE) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/utilities/matrix.cpp.s
.PHONY : utilities/matrix.cpp.s

utilities/transform.o: utilities/transform.cpp.o

.PHONY : utilities/transform.o

# target to build an object file
utilities/transform.cpp.o:
	$(MAKE) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/utilities/transform.cpp.o
.PHONY : utilities/transform.cpp.o

utilities/transform.i: utilities/transform.cpp.i

.PHONY : utilities/transform.i

# target to preprocess a source file
utilities/transform.cpp.i:
	$(MAKE) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/utilities/transform.cpp.i
.PHONY : utilities/transform.cpp.i

utilities/transform.s: utilities/transform.cpp.s

.PHONY : utilities/transform.s

# target to generate assembly for a file
utilities/transform.cpp.s:
	$(MAKE) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/utilities/transform.cpp.s
.PHONY : utilities/transform.cpp.s

utilities/vector.o: utilities/vector.cpp.o

.PHONY : utilities/vector.o

# target to build an object file
utilities/vector.cpp.o:
	$(MAKE) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/utilities/vector.cpp.o
.PHONY : utilities/vector.cpp.o

utilities/vector.i: utilities/vector.cpp.i

.PHONY : utilities/vector.i

# target to preprocess a source file
utilities/vector.cpp.i:
	$(MAKE) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/utilities/vector.cpp.i
.PHONY : utilities/vector.cpp.i

utilities/vector.s: utilities/vector.cpp.s

.PHONY : utilities/vector.s

# target to generate assembly for a file
utilities/vector.cpp.s:
	$(MAKE) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/utilities/vector.cpp.s
.PHONY : utilities/vector.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... sim"
	@echo "... camera.o"
	@echo "... camera.i"
	@echo "... camera.s"
	@echo "... dependencies/src/gl3w.o"
	@echo "... dependencies/src/gl3w.i"
	@echo "... dependencies/src/gl3w.s"
	@echo "... game.o"
	@echo "... game.i"
	@echo "... game.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... utilities/matrix.o"
	@echo "... utilities/matrix.i"
	@echo "... utilities/matrix.s"
	@echo "... utilities/transform.o"
	@echo "... utilities/transform.i"
	@echo "... utilities/transform.s"
	@echo "... utilities/vector.o"
	@echo "... utilities/vector.i"
	@echo "... utilities/vector.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

